apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f k8s/docker-compose.yml -o k8s/petclinic_chart/templates
    kompose.version: 1.22.0 (955b78124)
  labels:
    io.kompose.service: mysql-server
  name: mysql-server
spec:
  type: ExternalName
  externalName: petclinic.cbanmzptkrzf.us-east-1.rds.amazonaws.com


  # ports:
  #   - name: "3306"
  #     port: 3306
  #     targetPort: 3306
  # selector:
  #   io.kompose.service: mysql-server
